"""Re-cost both benchmark arms on every vendor model the ledger knows.

The paper's Table 3 counts distinct visual tokens served. What a vendor bills for
a frame depends on its downscaling rule, so the same frames cost different
amounts on different models and the ratio between the arms moves with them.
This script reads the image dimensions of every frame each arm was served and
prices them with nybls_core.ledger.tokens_for, whose formulas are checked
against the vendors' published tables in tests/test_ledger_models.py.

Coverage: Arm A from the 12 one shot packs (all frames present). Arm B from the
frames still on disk for rounds 2 to 4 (94 of 96 charged images; one file each
for oZAiHH9nrhk and 92gQUnMCA08 was deleted after the benchmark). Round 1 is
excluded from the per model table because its store has been used since the
benchmark and its frames directory no longer matches the round 1 ledger.
Grok is excluded because its token formula is unverified.

Usage: python bench/cost_by_model.py > bench/COST_BY_MODEL.md
"""
import glob
from pathlib import Path
import sys

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from nybls_core import ledger as led  # noqa: E402

STORE = Path.home() / ".nybls" / "store"
ROUNDS = {
    2: ["g9xUu2StOYg", "5oNHF72wbmI", "jgN4XWFUSb4"],
    3: ["L24Wf0VlTE0", "DQdB7wFEygo", "oZAiHH9nrhk", "PV3r6BINlsM"],
    4: ["92gQUnMCA08", "QtqYNyBv9r8", "Wlu4MsBnjuk", "vxP2PTA1GEk"],
}
MODELS = [m for m in led.MODELS if "unverified" not in led.MODELS[m]]


def dims(paths):
    return [Image.open(p).size for p in paths]


def main():
    a_dims, b_dims, cov = [], [], []
    for r, ids in ROUNDS.items():
        for mid in ids:
            a = sorted(glob.glob(str(STORE / mid / "oneshot" / "*.png")))
            b = sorted(p for p in glob.glob(str(STORE / mid / "frames" / "*.png"))
                       if not Path(p).name.startswith("_"))
            a_dims += dims(a); b_dims += dims(b)
            cov.append((r, mid, len(a), len(b)))
    print("# Cost of both arms by vendor model, rounds 2 to 4\n")
    print("Generated by `bench/cost_by_model.py` from the frames each arm was served, priced with")
    print("`nybls_core.ledger.tokens_for` (formulas checked against the vendors' published tables).")
    print("Distinct visual tokens served; a multi turn agent re-reads earlier images on every")
    print("call, so Arm B's API spend is higher by up to its call count.\n")
    print("| model | rule | Arm A tokens | Arm B tokens | A / B |")
    print("|---|---|---|---|---|")
    for m in MODELS:
        spec = led.MODELS[m]
        f = spec["formula"]
        if f == "anthropic":
            rule = f"28px cells, long edge {spec['max_edge']}, cap {spec['max_tokens']}"
        elif f == "openai-patch":
            rule = f"32px patches x{spec['multiplier']}, cap {spec['patch_cap']}"
        else:
            rule = "512px tiles, short side to 768"
        ta = sum(led.tokens_for(w, h, m) for w, h in a_dims)
        tb = sum(led.tokens_for(w, h, m) for w, h in b_dims)
        print(f"| {m} | {rule} | {ta:,} | {tb:,} | {ta / tb:.2f} |")
    print("\nCoverage (round, video, Arm A frames, Arm B frames on disk):")
    for c in cov:
        print(f"- {c[0]} {c[1]}: A {c[2]}, B {c[3]}")


if __name__ == "__main__":
    main()
